# Generated by Django 3.2.4 on 2021-06-04 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acd_year', models.TextField()),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'academic_year',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_no', models.TextField()),
                ('email', models.TextField()),
                ('photo', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faculty_department', to='RITSOFT_APP.department')),
            ],
            options={
                'db_table': 'faculty_details',
            },
        ),
        migrations.CreateModel(
            name='FacultyDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('hod', 'Head of the Department'), ('fclty', 'Faculty'), ('prncpl', 'Principal'), ('pgdean', 'PG Dean'), ('ugdean', 'UG Dean'), ('sadean', 'Student Affairs Dean'), ('stfadv', 'Staff Advisor')], default='faculty', max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faculty_id', to='RITSOFT_APP.facultydetails')),
            ],
            options={
                'db_table': 'faculty_designation',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hod_faculty', to='RITSOFT_APP.facultydetails'),
        ),
    ]
